In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)

(3,)
1
int32
3


In [4]:
b = np.array([4, 5, 6], dtype = 'int64')

In [5]:
a = [1, 'two', 3, 4]
print(a)

[1, 'two', 3, 4]


In [6]:
a = np.array([1, 'two', 3, 4])
a

array(['1', 'two', '3', '4'], dtype='<U11')

In [8]:
a = np.array([1, 'two', 3, 4], dtype = np.int32)
a

ValueError: invalid literal for int() with base 10: 'two'

## lab 11-1

In [9]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = [1, 2, 3, 4]
b = np.array(a)
b

array([1, 2, 3, 4])

In [18]:
c = np.array(range(0, 10, 2))
c

array([0, 2, 4, 6, 8])

In [19]:
print(c.shape)
print(c.ndim)
print(c.size)

(5,)
1
5


In [20]:
a = np.array([1, 2, 3])
print(a.max())
print(a.min())
print(a.mean())

3
1
2.0


In [21]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a.shape)

(3, 2)


In [24]:
b = a.flatten()
print(b.shape)

(3,)


In [27]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b.shape

(2, 3)

In [29]:
np.append([a], b, axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.random.rand(3, 3)

array([[0.04744948, 0.09922673, 0.34630726],
       [0.0069273 , 0.62707716, 0.22079814],
       [0.41682358, 0.19941528, 0.93036676]])

In [31]:
np.random.randint(0, 10, size = 10)

array([1, 5, 7, 4, 9, 2, 8, 6, 2, 4])

In [32]:
a = [1, 2, 3]
b = [4, 5, 6]
a+b

[1, 2, 3, 4, 5, 6]

In [33]:
result = []
for i in range(len(a)):
    result.append(a[i]+b[i])

print(result)

[5, 7, 9]


In [34]:
a = np.array(a)
b = np.array(b)

In [35]:
c = a + b

In [36]:
c

array([5, 7, 9])

In [37]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])
a+b

array([[11, 22],
       [33, 44]])

In [38]:
print(a-b)
print(a*b)
print(a/b)

[[ -9 -18]
 [-27 -36]]
[[ 10  40]
 [ 90 160]]
[[0.1 0.1]
 [0.1 0.1]]


In [39]:
np.matmul(a, b)

array([[ 70, 100],
       [150, 220]])

In [40]:
a@b

array([[ 70, 100],
       [150, 220]])

In [41]:
a

array([[1, 2],
       [3, 4]])

In [42]:
a+1

array([[2, 3],
       [4, 5]])

In [44]:
a**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)